[tool.poetry]
name = "tagcleaner"
version = "0.1.0"
description = ""
authors = ["Anze Pecar <anze@pecar.me>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
